### ISSUE TITLE
windows安装报错

### ISSUE THREAD

**Issue by Joytracy** [lihuacai168/AnotherFasterRunner#32]
C:\Users\admin\Desktop\AnotherFasterRunner>pip install -r requirements.txt
ERROR: Exception:
Traceback (most recent call last):                                                                                                            
  File "C:\Users\admin\Desktop\AnotherFasterRunner\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)                                                                                                                  
  File "C:\Users\admin\Desktop\AnotherFasterRunner\venv\lib\site-packages\pip\_internal\req\req_file.py", line 327, in parse
    yield from self._parse_and_recurse(filename, constraint)
  File "C:\Users\admin\Desktop\AnotherFasterRunner\venv\lib\site-packages\pip\_internal\req\req_file.py", line 332, in _parse_and_recurse
    for line in self._parse_file(filename, constraint):
  File "C:\Users\admin\Desktop\AnotherFasterRunner\venv\lib\site-packages\pip\_internal\req\req_file.py", line 363, in _parse_file
    _, content = get_file_content(filename, self._session)
  File "C:\Users\admin\Desktop\AnotherFasterRunner\venv\lib\site-packages\pip\_internal\req\req_file.py", line 541, in get_file_content
    content = auto_decode(f.read())
  File "C:\Users\admin\Desktop\AnotherFasterRunner\venv\lib\site-packages\pip\_internal\utils\encoding.py", line 34, in auto_decode
    return data.decode(
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 1311: illegal multibyte sequence

**Comment by Joytracy** [comment]
python 版本 3.9.1
