### ISSUE TITLE
部署不成功

### ISSUE THREAD

**Issue by KerryPeng08** [lihuacai168/AnotherFasterRunner#44]
按照你的文档，部署失败，感觉部署这块能不能讲的详细一点，也因为部署特别熟悉这一块

**Comment by lihuacai168** [comment]
> 按照你的文档，部署失败，感觉部署这块能不能讲的详细一点，也因为部署特别熟悉这一块

需要你提供你的操作步骤，系统环境，失败的截图等
部署步骤已经做了很多次优化，尽量达到一键部署

**Comment by KerryPeng08** [comment]
本地运行的时候提示这个：

kerry.peng@kerry AnotherFasterRunner-master % python3 manage.py runserver 0.0.0.0:8000 --settings=FasterRunner.settings.pro
2023-04-06 15:17:15,319 [none] django.utils.autoreload INFO [pid:86705] [autoreload.py->run_with_reloader:597] Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kerry.peng/Library/Python/3.7/lib/python/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/Users/kerry.peng/Library/Python/3.7/lib/python/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/Users/kerry.peng/Library/Python/3.7/lib/python/site-packages/django/utils/autoreload.py", line 77, in raise_last_exception
    raise _exception[1]
  File "/Users/kerry.peng/Library/Python/3.7/lib/python/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/kerry.peng/Library/Python/3.7/lib/python/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/Users/kerry.peng/Library/Python/3.7/lib/python/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/kerry.peng/Library/Python/3.7/lib/python/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Users/kerry.peng/Library/Python/3.7/lib/python/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/kerry.peng/Documents/AnotherFasterRunner-master/fastrunner/models.py", line 3, in <module>
    from django_celery_beat.models import PeriodicTask
  File "/Users/kerry.peng/Library/Python/3.7/lib/python/site-packages/django_celery_beat/models.py", line 10, in <module>
    from celery import current_app, schedules
  File "/Users/kerry.peng/Library/Python/3.7/lib/python/site-packages/celery/schedules.py", line 12, in <module>
    from . import current_app
ImportError: cannot import name 'current_app' from 'celery' (/Users/kerry.peng/Library/Python/3.7/lib/python/site-packages/celery/__init__.py)

**Comment by KerryPeng08** [comment]
Docker-Compose的方式前端能启动起来了，但是docker那里一直报链接不上DB，感觉这个部署容易出错

**Comment by KerryPeng08** [comment]
因为我看好几个配置文件，每个需要配置什么地址，我看的有点懵，所以很容易出错

**Comment by lihuacai168** [comment]
> 本地运行的时候提示这个：
> 
> kerry.peng@kerry AnotherFasterRunner-master % python3 manage.py runserver 0.0.0.0:8000 --settings=FasterRunner.settings.pro 2023-04-06 15:17:15,319 [none] django.utils.autoreload INFO [pid:86705] [autoreload.py->run_with_reloader:597] Watching for file changes with StatReloader Exception in thread django-main-thread: Traceback (most recent call last): File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner self.run() File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run self._target(*self._args, **self._kwargs) File "/Users/kerry.peng/Library/Python/3.7/lib/python/site-packages/django/utils/autoreload.py", line 54, in wrapper fn(*args, **kwargs) File "/Users/kerry.peng/Library/Python/3.7/lib/python/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run autoreload.raise_last_exception() File "/Users/kerry.peng/Library/Python/3.7/lib/python/site-packages/django/utils/autoreload.py", line 77, in raise_last_exception raise _exception[1] File "/Users/kerry.peng/Library/Python/3.7/lib/python/site-packages/django/core/management/**init**.py", line 337, in execute autoreload.check_errors(django.setup)() File "/Users/kerry.peng/Library/Python/3.7/lib/python/site-packages/django/utils/autoreload.py", line 54, in wrapper fn(*args, **kwargs) File "/Users/kerry.peng/Library/Python/3.7/lib/python/site-packages/django/**init**.py", line 24, in setup apps.populate(settings.INSTALLED_APPS) File "/Users/kerry.peng/Library/Python/3.7/lib/python/site-packages/django/apps/registry.py", line 114, in populate app_config.import_models() File "/Users/kerry.peng/Library/Python/3.7/lib/python/site-packages/django/apps/config.py", line 211, in import_models self.models_module = import_module(models_module_name) File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/**init**.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1006, in _gcd_import File "", line 983, in _find_and_load File "", line 967, in _find_and_load_unlocked File "", line 677, in _load_unlocked File "", line 728, in exec_module File "", line 219, in _call_with_frames_removed File "/Users/kerry.peng/Documents/AnotherFasterRunner-master/fastrunner/models.py", line 3, in from django_celery_beat.models import PeriodicTask File "/Users/kerry.peng/Library/Python/3.7/lib/python/site-packages/django_celery_beat/models.py", line 10, in from celery import current_app, schedules File "/Users/kerry.peng/Library/Python/3.7/lib/python/site-packages/celery/schedules.py", line 12, in from . import current_app ImportError: cannot import name 'current_app' from 'celery' (/Users/kerry.peng/Library/Python/3.7/lib/python/site-packages/celery/**init**.py)

<img width="303" alt="image" src="https://user-images.githubusercontent.com/11568297/230311115-378f5861-704d-46e1-9445-d7dc4d9e5539.png">
这么大的提示为啥不看

**Comment by lihuacai168** [comment]
> 因为我看好几个配置文件，每个需要配置什么地址，我看的有点懵，所以很容易出错

哪个几个配置文件，哪些不懂，哪里懵
你不详细指出来，我想帮你都帮不了
DB连不上，叫你发截图，也没发呀

**Comment by KerryPeng08** [comment]
谢谢，我先把python 3.9这个搞定了再看下有没有问题

**Comment by KerryPeng08** [comment]
# 指定配置文件启动, .env需要绝对路径
docker-compose --env-file=$HOME/.env up --build -d
我用的这个命令来启动的

这个是$HOME/.env文件里面的配置，请问下这个里面的数据库是要填什么地址呢，我本地已经安装好了mysql，我是不是把本地的哪些地址配置上去就可以了，但是我把本地的地址配置上去之后会提示：Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:3306 -> 0.0.0.0:0: listen tcp 0.0.0.0:3306: bind: address already in use

# MySQL
MYSQL_ROOT_PASSWORD=12345678
MYSQL_USER=root
MYSQL_PASSWORD=12345678
MYSQL_DATABASE=fastRunnerApiTest  # set default database name
MYSQL_PORT_OUT=3306  # expose port
MYSQL_HOST=localhost # only use only pro.py, docker.py don't need it

**Comment by lihuacai168** [comment]
> 

不需要本地安装db
MYSQL_HOST，这些写`db`，这个是`docker-compose` service的名称
MYSQL_PORT_OUT，这个是db对外暴露的端口号，写3306，就跟宿主机的冲突了，改成其他的，在docker容器中，不能写localhost

**Comment by KerryPeng08** [comment]
# MySQL
MYSQL_ROOT_PASSWORD=faster12356
MYSQL_USER=faster
MYSQL_PASSWORD=faster2019
MYSQL_DATABASE=db_faster  # set default database name
MYSQL_PORT_OUT=13306  # expose port
MYSQL_HOST=127.0.0.1 # only use only pro.py, docker.py don't need it

PLATFORM_NAME=FasterRunner

配置成这样是对的吗，这个数据库是我用你下面docker创建的，对docker实在不熟悉 哈哈

**Comment by lihuacai168** [comment]
> # MySQL
> MYSQL_ROOT_PASSWORD=faster12356 MYSQL_USER=faster MYSQL_PASSWORD=faster2019 MYSQL_DATABASE=db_faster # set default database name MYSQL_PORT_OUT=13306 # expose port MYSQL_HOST=127.0.0.1 # only use only pro.py, docker.py don't need it
> 
> PLATFORM_NAME=FasterRunner
> 
> 配置成这样是对的吗，这个数据库是我用你下面docker创建的，对docker实在不熟悉 哈哈

你能认真一点吗？
<img width="747" alt="image" src="https://user-images.githubusercontent.com/11568297/230339196-5d58abe7-a7ac-4d12-8f4a-f79189c5d105.png">

**Comment by lihuacai168** [comment]
这个issue我直接关了，你先认真看完文档，补充一下docker知识，有问题再另外开新的issue
或者你确实不想看，懒得看，那也是可以的。直接找我付费1对1咨询就行
